# Generated by Django 5.2.8 on 2025-12-09 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECTOR', 'Director/a Clínica'), ('SUPERVISOR', 'Abogado/a Supervisor/a'), ('ESTUDIANTE', 'Estudiante/Clínico'), ('SECRETARIA', 'Secretaría/Apoyo'), ('EXTERNO', 'Persona Atendida')], default='ESTUDIANTE', max_length=20, verbose_name='Rol')),
                ('sede', models.CharField(blank=True, choices=[('SANTIAGO', 'Santiago - Campus Bellavista'), ('CONCEPCION', 'Concepción - Campus Las Tres Pascualas'), ('VALDIVIA', 'Valdivia - Campus General Lagos'), ('PUERTO_MONTT', 'Puerto Montt - Campus Pichi Pelluco'), ('OSORNO', 'Osorno - Campus Osorno')], max_length=20, null=True, verbose_name='Sede USS')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
