# Generated by Django 5.2.8 on 2025-12-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del tribunal')),
                ('tipo', models.CharField(choices=[('JUZ_CIVIL', 'Juzgado de Letras en lo Civil'), ('JUZ_LABORAL', 'Juzgado de Letras del Trabajo'), ('JUZ_COBRANZA', 'Juzgado de Cobranza Laboral y Previsional'), ('JUZ_FAMILIA', 'Juzgado de Familia'), ('JUZ_GARANTIA', 'Juzgado de Garantía'), ('TOP', 'Tribunal de Juicio Oral en lo Penal'), ('JUZ_LETRAS', 'Juzgado de Letras (Competencia Común)'), ('CORTE_AP', 'Corte de Apelaciones'), ('CORTE_SUPREMA', 'Corte Suprema'), ('JPL', 'Juzgado de Policía Local'), ('TRIB_MILITAR', 'Tribunal Militar'), ('TRIB_AMBIENTAL', 'Tribunal Ambiental'), ('TRIB_CONTRATACION', 'Tribunal de Contratación Pública'), ('TRIB_TRIBUTARIO', 'Tribunal Tributario y Aduanero'), ('TRIB_PROPIEDAD', 'Tribunal de Propiedad Industrial'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de tribunal')),
                ('region', models.CharField(choices=[('RM', 'Región Metropolitana'), ('BIOBIO', 'Región del Biobío'), ('LOS_RIOS', 'Región de Los Ríos'), ('LOS_LAGOS', 'Región de Los Lagos')], max_length=20, verbose_name='Región')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código interno')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunales',
                'ordering': ['region', 'ciudad', 'tipo', 'nombre'],
            },
        ),
    ]
