# Generated by Django 5.2.8 on 2025-12-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_tribunal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la materia')),
                ('tipo_tribunal', models.CharField(choices=[('JUZ_CIVIL', 'Civil'), ('JUZ_LABORAL', 'Laboral'), ('JUZ_COBRANZA', 'Cobranza Laboral'), ('JUZ_FAMILIA', 'Familia'), ('JUZ_GARANTIA', 'Penal (Garantía)'), ('TOP', 'Penal (Juicio Oral)'), ('JUZ_LETRAS', 'Competencia Común'), ('CORTE_AP', 'Corte de Apelaciones'), ('CORTE_SUPREMA', 'Corte Suprema'), ('JPL', 'Policía Local'), ('TRIB_MILITAR', 'Militar'), ('TRIB_AMBIENTAL', 'Ambiental'), ('TRIB_CONTRATACION', 'Contratación Pública'), ('TRIB_TRIBUTARIO', 'Tributario y Aduanero'), ('TRIB_PROPIEDAD', 'Propiedad Industrial'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de tribunal')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['tipo_tribunal', 'nombre'],
                'unique_together': {('nombre', 'tipo_tribunal')},
            },
        ),
    ]
