# Generated by Django 5.2.8 on 2025-12-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('JUDICIAL_ENTRADA', 'Judicial (recibido del tribunal)'), ('JUDICIAL_SALIDA', 'Judicial (presentado al tribunal)'), ('INTERNO', 'Documento interno'), ('PRUEBA', 'Medio de prueba'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requiere_folio', models.BooleanField(default=False, verbose_name='Requiere folio')),
                ('requiere_fecha_emision', models.BooleanField(default=False, verbose_name='Requiere fecha de emisión')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
