# Generated by Django 5.2.8 on 2025-12-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(choices=[('gray', 'Gris'), ('blue', 'Azul'), ('yellow', 'Amarillo'), ('green', 'Verde'), ('red', 'Rojo'), ('orange', 'Naranjo'), ('purple', 'Morado')], default='gray', max_length=20, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en el flujo procesal (menor = más temprano)', verbose_name='Orden')),
                ('es_final', models.BooleanField(default=False, help_text='Marca si este estado cierra/archiva la causa', verbose_name='Es estado final')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado de causa',
                'verbose_name_plural': 'Estados de causa',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
