# Generated by Django 5.2.8 on 2025-12-09 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_estadocausa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='causa',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Causa', 'verbose_name_plural': 'Causas'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='causa',
            name='caratula',
            field=models.CharField(max_length=200, verbose_name='Carátula'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causas', to='gestion.estadocausa', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causas', to='gestion.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='rit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RIT'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causas', to='gestion.tribunal', verbose_name='Tribunal'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.causa', verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='gestion.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
