# Generated by Django 5.2.8 on 2025-12-09 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_causa_options_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_vulnerable',
            field=models.BooleanField(default=False, verbose_name='¿Es vulnerable?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('CONVIVIENTE', 'Conviviente civil'), ('SEPARADO', 'Separado/a'), ('NI', 'No informa')], default='NI', max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('NI', 'No informa')], default='NI', max_length=2, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(default='Chilena', max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='persona',
            name='region',
            field=models.CharField(blank=True, choices=[('RM', 'Región Metropolitana'), ('BIOBIO', 'Región del Biobío'), ('LOS_RIOS', 'Región de Los Ríos'), ('LOS_LAGOS', 'Región de Los Lagos'), ('OTRA', 'Otra región')], max_length=20, null=True, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='persona',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del representante'),
        ),
        migrations.AddField(
            model_name='persona',
            name='representante_run',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RUN del representante'),
        ),
        migrations.AddField(
            model_name='persona',
            name='representante_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del representante'),
        ),
        migrations.AddField(
            model_name='persona',
            name='requiere_representante',
            field=models.BooleanField(default=False, help_text='Marcar si es menor de edad o tiene incapacidad', verbose_name='¿Requiere representante?'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(choices=[('ATENDIDO', 'Persona atendida'), ('CONTRAPARTE', 'Contraparte'), ('TESTIGO', 'Testigo'), ('PERITO', 'Perito'), ('TERCERO', 'Tercero interesado'), ('OTRO', 'Otro')], default='ATENDIDO', max_length=20, verbose_name='Tipo de persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='vulnerabilidad',
            field=models.TextField(blank=True, help_text='Describir situación de vulnerabilidad si aplica', null=True, verbose_name='Descripción de vulnerabilidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='run',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUN'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
