# Generated by Django 5.2.8 on 2025-12-09 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_persona_options_persona_activo_persona_comuna_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DATOS_PERSONALES', 'Tratamiento de datos personales'), ('NOTIFICACIONES', 'Recibir notificaciones'), ('COMPARTIR_INFO', 'Compartir información con terceros'), ('USO_ACADEMICO', 'Uso del caso con fines académicos'), ('GRABACION', 'Grabación de entrevistas'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de consentimiento')),
                ('otorgado', models.BooleanField(default=False, verbose_name='¿Consentimiento otorgado?')),
                ('fecha_otorgamiento', models.DateField(blank=True, null=True, verbose_name='Fecha de otorgamiento')),
                ('fecha_revocacion', models.DateField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('documento_respaldo', models.FileField(blank=True, help_text='Consentimiento firmado escaneado', null=True, upload_to='consentimientos/', verbose_name='Documento de respaldo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='gestion.persona', verbose_name='Persona')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-fecha_registro'],
                'unique_together': {('persona', 'tipo')},
            },
        ),
    ]
