# Generated by Django 5.2.8 on 2025-12-09 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_consentimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento_padre',
            field=models.ForeignKey(blank=True, help_text='Si es una nueva versión, indicar el documento original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones', to='gestion.documento', verbose_name='Documento original'),
        ),
        migrations.AddField(
            model_name='documento',
            name='emisor',
            field=models.CharField(blank=True, help_text='Tribunal, institución o persona que emite el documento', max_length=200, null=True, verbose_name='Emisor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='es_confidencial',
            field=models.BooleanField(default=False, help_text='Marcar si contiene información sensible', verbose_name='¿Es confidencial?'),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINAL', 'Final'), ('ANULADO', 'Anulado')], default='FINAL', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha del documento (ej: fecha de la resolución)', null=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='documento',
            name='folio',
            field=models.PositiveIntegerField(blank=True, help_text='Número de folio en el expediente', null=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='documento',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de oficio, resolución, rol, etc.', max_length=50, null=True, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
    ]
