# Generated by Django 5.2.8 on 2025-12-09 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_documento_documento_padre_documento_emisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiencia',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Audiencia', 'verbose_name_plural': 'Audiencias'},
        ),
        migrations.RemoveField(
            model_name='audiencia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='audiencia',
            name='asistio_cliente',
            field=models.BooleanField(default=False, verbose_name='¿Asistió el cliente?'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='asistio_estudiante',
            field=models.BooleanField(default=False, verbose_name='¿Asistió el estudiante?'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='asistio_supervisor',
            field=models.BooleanField(default=False, verbose_name='¿Asistió el supervisor?'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='audiencia_anterior',
            field=models.ForeignKey(blank=True, help_text='Si es reprogramación, indicar la audiencia original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones', to='gestion.audiencia', verbose_name='Audiencia anterior'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiencias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='duracion_estimada',
            field=models.PositiveIntegerField(default=60, verbose_name='Duración estimada (minutos)'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('SUSPENDIDA', 'Suspendida'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiencia',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='fecha_recordatorio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío de recordatorio'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='motivo_suspension',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de suspensión/reprogramación'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio enviado'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='resultado',
            field=models.TextField(blank=True, help_text='Descripción de lo ocurrido en la audiencia', null=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='sala',
            field=models.CharField(blank=True, help_text='Número de sala si aplica', max_length=50, null=True, verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='tipo_evento',
            field=models.CharField(choices=[('AUDIENCIA_JUDICIAL', 'Audiencia judicial'), ('ENTREVISTA_CLIENTE', 'Entrevista con cliente'), ('REUNION_EQUIPO', 'Reunión de equipo'), ('REUNION_SUPERVISOR', 'Reunión con supervisor'), ('COMPARENDO', 'Comparendo'), ('MEDIACION', 'Mediación'), ('OTRO', 'Otro')], default='AUDIENCIA_JUDICIAL', max_length=20, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='causa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='gestion.causa', verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
