# Generated by Django 5.2.8 on 2025-12-09 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_audiencia_options_remove_audiencia_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('VER', 'Ver'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('SUBIR_DOC', 'Subir documento'), ('DESCARGAR_DOC', 'Descargar documento'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('ASIGNAR', 'Asignar responsable'), ('OTRO', 'Otro')], max_length=20, verbose_name='Acción')),
                ('modelo', models.CharField(choices=[('CAUSA', 'Causa'), ('PERSONA', 'Persona'), ('DOCUMENTO', 'Documento'), ('AUDIENCIA', 'Audiencia'), ('CONSENTIMIENTO', 'Consentimiento'), ('USUARIO', 'Usuario'), ('OTRO', 'Otro')], max_length=20, verbose_name='Modelo afectado')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('objeto_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Representación del objeto')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado del objeto antes del cambio', null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado del objeto después del cambio', null=True, verbose_name='Datos nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
