# Generated by Django 5.2.8 on 2025-12-11 04:10

import apps.gestion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_logauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='rit',
            field=models.CharField(blank=True, help_text='Formato: C-1234-2024', max_length=20, validators=[apps.gestion.validators.validar_rit], verbose_name='RIT'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='ruc',
            field=models.CharField(blank=True, help_text='Formato: 2400123456-7', max_length=20, validators=[apps.gestion.validators.validar_ruc], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[apps.gestion.validators.validar_fecha_nacimiento], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='run',
            field=models.CharField(help_text='Formato: 12.345.678-9', max_length=12, unique=True, validators=[apps.gestion.validators.validar_rut_chileno], verbose_name='RUN'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, help_text='Formato: +56 9 1234 5678', max_length=20, validators=[apps.gestion.validators.validar_telefono_chileno], verbose_name='Teléfono'),
        ),
    ]
