# Generated by Django 5.2.8 on 2025-12-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_causa_rit_alter_causa_ruc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='causa',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Antecedentes y contexto del caso', verbose_name='Descripción del caso'),
        ),
        migrations.AddField(
            model_name='causa',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas internas para el equipo de la clínica jurídica', verbose_name='Observaciones internas'),
        ),
    ]
