# Generated by Django 5.2.8 on 2025-12-11 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_causa_descripcion_causa_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocausa',
            options={'ordering': ['orden'], 'verbose_name': 'Estado de Causa', 'verbose_name_plural': 'Estados de Causa'},
        ),
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Log de Auditoría', 'verbose_name_plural': 'Logs de Auditoría'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-id'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='audiencia',
            index=models.Index(fields=['causa'], name='audiencia_causa_idx'),
        ),
        migrations.AddIndex(
            model_name='audiencia',
            index=models.Index(fields=['fecha_hora'], name='audiencia_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='audiencia',
            index=models.Index(fields=['-fecha_hora'], name='audiencia_fecha_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='audiencia',
            index=models.Index(fields=['estado'], name='audiencia_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='audiencia',
            index=models.Index(fields=['tipo_evento'], name='audiencia_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='audiencia',
            index=models.Index(fields=['fecha_hora', 'estado'], name='audiencia_fecha_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['rit'], name='causa_rit_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['ruc'], name='causa_ruc_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['caratula'], name='causa_caratula_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['estado'], name='causa_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['tribunal'], name='causa_tribunal_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['materia'], name='causa_materia_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['responsable'], name='causa_responsable_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['fecha_creacion'], name='causa_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='causa',
            index=models.Index(fields=['-fecha_creacion'], name='causa_fecha_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['causa'], name='documento_causa_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tipo'], name='documento_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['usuario'], name='documento_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['titulo'], name='documento_titulo_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha_subida'], name='documento_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['-fecha_subida'], name='documento_fecha_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['estado'], name='documento_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='estadocausa',
            index=models.Index(fields=['orden'], name='estado_orden_idx'),
        ),
        migrations.AddIndex(
            model_name='estadocausa',
            index=models.Index(fields=['activo'], name='estado_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='estadocausa',
            index=models.Index(fields=['es_final'], name='estado_final_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario'], name='log_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['accion'], name='log_accion_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modelo'], name='log_modelo_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['fecha'], name='log_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['-fecha'], name='log_fecha_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['objeto_id'], name='log_objeto_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modelo', 'objeto_id'], name='log_modelo_objeto_idx'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['tipo_tribunal'], name='materia_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='materia',
            index=models.Index(fields=['activo'], name='materia_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['run'], name='persona_run_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['nombres', 'apellidos'], name='persona_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['email'], name='persona_email_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['tipo_persona'], name='persona_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['activo'], name='persona_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='tipodocumento',
            index=models.Index(fields=['categoria'], name='tipo_doc_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='tipodocumento',
            index=models.Index(fields=['activo'], name='tipo_doc_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunal',
            index=models.Index(fields=['tipo'], name='tribunal_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunal',
            index=models.Index(fields=['region'], name='tribunal_region_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunal',
            index=models.Index(fields=['ciudad'], name='tribunal_ciudad_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunal',
            index=models.Index(fields=['activo'], name='tribunal_activo_idx'),
        ),
    ]
