# Generated by Django 5.2.8 on 2025-12-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_estadocausa_options_alter_logauditoria_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consentimiento',
            unique_together=set(),
        ),
    ]
